import type { Metadata } from 'next';
import { Footer, Header, SocialMedia } from '@/components';
import { bodyFont } from '@/config';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={bodyFont.className}>
        <div className='main-container'>
          <Header />
          <main>{children}</main>
          <SocialMedia />
          <Footer />
        </div>
      </body>
    </html>
  );
}
