import type { Metadata } from 'next';
import { Footer, Header } from '@/components';
import { bodyFont } from '@/config';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={bodyFont.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
