export * from './project.interface';
export * from './locales.interface';
export * from './dictionary.interface';
export * from './skill.interface';
export * from './post.interface';
export * from './header.interface';
export * from './postDetail.interface';
export * from './botMessages.interface';
export * from './metadata.interface';
